## Basic cleaning

In [62]:
import pandas as pd

In [63]:
original_pop_db = pd.read_excel('population.xlsx')
original_pop_db.head(10)

,ANO,GEO_COD,GEO_COD_DSG,NIVEL,NIVEL_DSG,N_INDIVIDUOS_RESIDENT,N_INDIVIDUOS_RESIDENT_H,N_INDIVIDUOS_RESIDENT_M
0,2011,'PT,PT,1,Total Nacional,10562178,5046600,5515578
1,2011,'1,Continente,2,NUT1,10047621,4798798,5248823
2,2011,'17,Lisboa,3,NUT2,2821876,1334605,1487271
3,2011,'171,Grande Lisboa,4,NUT3,2042477,961132,1081345
4,2011,'1106,Lisboa,5,Municipio,547733,250874,296859
5,2011,'110601,Ajuda,6,Freguesia,15584,7120,8464
6,2011,'110602,Alcântara,6,Freguesia,13943,6254,7689
7,2011,'110603,Alto do Pina,6,Freguesia,10333,4687,5646
8,2011,'110604,Alvalade,6,Freguesia,8869,3764,5105
9,2011,'110605,Ameixoeira,6,Freguesia,11863,5568,6295

In [64]:
# Selecting just the cols that we want to display

pop_db = pd.read_excel('population.xlsx')
pop_db = pop_db[['GEO_COD_DSG', 'NIVEL_DSG', 'N_INDIVIDUOS_RESIDENT']]
pop_db.head(20)

         GEO_COD_DSG       NIVEL_DSG  N_INDIVIDUOS_RESIDENT
0                 PT  Total Nacional               10562178
1         Continente            NUT1               10047621
2             Lisboa            NUT2                2821876
3      Grande Lisboa            NUT3                2042477
4             Lisboa       Municipio                 547733
5              Ajuda       Freguesia                  15584
6          Alcântara       Freguesia                  13943
7       Alto do Pina       Freguesia                  10333
8           Alvalade       Freguesia                   8869
9         Ameixoeira       Freguesia                  11863
10             Anjos       Freguesia                   9361
11             Beato       Freguesia                  12429
12           Benfica       Freguesia                  36821
13      Campo Grande       Freguesia                  10514
14         Campolide       Freguesia                  15460
15           Carnide       Freguesia                  23316
16           Castelo       Freguesia                    355
17          Charneca       Freguesia                   9935
18  Coração de Jesus       Freguesia                   3689
19        Encarnação       Freguesia                   2252

In [65]:
# Renaming the columns

pop_db.columns = ['Freguesia', 'Type', 'Total Residents']

In [66]:
pop_db.head(10)

       Freguesia            Type  Total Residents
0             PT  Total Nacional         10562178
1     Continente            NUT1         10047621
2         Lisboa            NUT2          2821876
3  Grande Lisboa            NUT3          2042477
4         Lisboa       Municipio           547733
5          Ajuda       Freguesia            15584
6      Alcântara       Freguesia            13943
7   Alto do Pina       Freguesia            10333
8       Alvalade       Freguesia             8869
9     Ameixoeira       Freguesia            11863

In [67]:
# Here we are just selecting the 'freguesia' type to be displayed

pop_db = pop_db[(pop_db['Type']=='Freguesia')]

pop_db.head(10)

       Freguesia       Type  Total Residents
5          Ajuda  Freguesia            15584
6      Alcântara  Freguesia            13943
7   Alto do Pina  Freguesia            10333
8       Alvalade  Freguesia             8869
9     Ameixoeira  Freguesia            11863
10         Anjos  Freguesia             9361
11         Beato  Freguesia            12429
12       Benfica  Freguesia            36821
13  Campo Grande  Freguesia            10514
14     Campolide  Freguesia            15460

In [68]:
pop_db.shape

(53, 3)

In [69]:
original_freguesias_db = pd.read_csv('Freguesias2012.csv')
original_freguesias_db.head(20)

,OBJECTID,COD_SIG,NOME,IDTIPO,PERIMETRO,AREA_M2,FREGUESIAS53,GlobalID,Shape__Area,Shape__Length
0,1,122,Santo António,4015,6313.94,1494348.58,Coração de Jesus + São José + São Mamede,9de1ceba-f851-4181-a39b-a4f8bc15f3c5,2.458057e+06,8097.074172
1,2,118,Parque das Nações,4015,12237.24,5435124.30,Santa Maria dos Olivais,aee6efb3-c624-4d82-b5f8-a98c4444b8c6,8.953807e+06,15724.284710
2,3,115,Marvila,4015,12216.54,7122521.90,Marvila,d6c144c0-6ffc-46d7-b6bf-f10fa7977b89,1.172476e+07,15674.400259
3,4,101,Ajuda,4015,9153.10,2876647.11,Ajuda,cdcaeb5c-7228-4a89-9091-9fb9be097e6e,4.730508e+06,11740.588160
4,5,104,Areeiro,4015,6358.83,1719002.47,Alto do Pina + São João de Deus,d1e276ef-009e-4290-a8b8-73643141a71e,2.829203e+06,8153.225327
5,6,121,Santa Maria Maior,4015,9306.07,3011591.52,Castelo + Madalena + Mártires + Sacramento +Sa...,60af311b-84fb-4a39-856a-291d65993f97,4.952034e+06,11936.070712
6,7,103,Alvalade,4015,10751.30,5341751.02,Alvalade + Campo Grande + São João de Brito,e9ec7868-7b40-478a-87b3-c6ad6e373e5a,8.794657e+06,13786.968033
7,8,108,Belém,4015,16050.78,10426948.88,Santa Maria de Belém + São Francisco Xavier,3a6d0af1-130a-4c90-80f6-b6017dac1ca1,1.713895e+07,20577.231795
8,9,113,Estrela,4015,9927.92,4604095.97,Lapa + Prazeres + Santos-o-Velho,ba35868d-aa59-40db-8737-469f48274ce9,7.569528e+06,12734.386771
9,10,105,Arroios,4015,8240.38,2127871.88,Anjos + Pena + São Jorge de Arroios,ec8fa8b1-49e5-49bb-a311-1f51aafa5e77,3.500783e+06,10572.552949
10,11,120,Santa Clara,4015,9431.48,3355562.58,Ameixoeira + Charneca,7c409727-e07d-41bf-bc65-18b3c4c619a2,5.529409e+06,12107.747775
11,12,106,Avenidas Novas,4015,8789.86,2994523.99,Nossa Senhora de Fátima + São Sebastião da Ped...,4dba39f3-c22c-4e53-83b3-a884e5c8f731,4.927916e+06,11274.864029
12,13,112,Carnide,4015,10445.19,3688827.32,Carnide,355aaafc-030e-46a2-95ca-0fe725545b8b,6.075093e+06,13404.426050
13,14,123,São Domingos de Benfica,4015,10009.46,4294403.21,São Domingos de Benfica,c2c273ab-e383-4cc7-a0d9-3fd280e0b8e9,7.068743e+06,12839.997937
14,15,107,Beato,4015,8329.64,2483775.04,Beato,1f3c537a-f720-4187-bff9-19f9389a419e,4.086759e+06,10685.118420
15,16,111,Campolide,4015,8506.73,2774372.95,Campolide,bfe7ec0e-76af-4a58-ad15-8de847b2faf7,4.564789e+06,10906.671317
16,17,102,Alcântara,4015,11258.45,5074843.76,Alcântara,921cf6af-b88c-47ea-8eda-ea6ca6680e89,8.344777e+06,14443.931054
17,18,110,Campo de Ourique,4015,6605.93,1651405.17,Santa Isabel + Santo Condestável,16b4ad84-3f12-4655-8a82-a7dfed75ec8d,2.716167e+06,8472.132470
18,19,124,São Vicente,4015,6997.46,1985855.99,Graça + Santa Engrácia + São Vicente de Fora,b122835b-4614-4f7b-87c4-fd3153d9b27b,3.266135e+06,8974.770361
19,20,117,Olivais,4015,12584.00,8088293.95,Santa Maria dos Olivais,775c657a-8172-462d-af7c-394587eb8a86,1.332305e+07,16147.938031

In [70]:
freguesia_db = original_freguesias_db[['NOME', 'AREA_M2', 'FREGUESIAS53']]
freguesia_db.head(50)

,NOME,AREA_M2,FREGUESIAS53
0,Santo António,1494348.58,Coração de Jesus + São José + São Mamede
1,Parque das Nações,5435124.30,Santa Maria dos Olivais
2,Marvila,7122521.90,Marvila
3,Ajuda,2876647.11,Ajuda
4,Areeiro,1719002.47,Alto do Pina + São João de Deus
5,Santa Maria Maior,3011591.52,Castelo + Madalena + Mártires + Sacramento +Sa...
6,Alvalade,5341751.02,Alvalade + Campo Grande + São João de Brito
7,Belém,10426948.88,Santa Maria de Belém + São Francisco Xavier
8,Estrela,4604095.97,Lapa + Prazeres + Santos-o-Velho
9,Arroios,2127871.88,Anjos + Pena + São Jorge de Arroios
10,Santa Clara,3355562.58,Ameixoeira + Charneca
11,Avenidas Novas,2994523.99,Nossa Senhora de Fátima + São Sebastião da Ped...
12,Carnide,3688827.32,Carnide
13,São Domingos de Benfica,4294403.21,São Domingos de Benfica
14,Beato,2483775.04,Beato
15,Campolide,2774372.95,Campolide
16,Alcântara,5074843.76,Alcântara
17,Campo de Ourique,1651405.17,Santa Isabel + Santo Condestável
18,São Vicente,1985855.99,Graça + Santa Engrácia + São Vicente de Fora
19,Olivais,8088293.95,Santa Maria dos Olivais
20,Misericórdia,2192198.78,Encarnação + Mercês + Santa Catarina + São Paulo
21,Lumiar,6574930.77,Lumiar
22,Penha de França,2710760.87,Penha de França + São João
23,Benfica,8024544.82,Benfica

In [71]:
freguesia_db.columns = ['Current Freguesias', 'Area', 'Old Freguesias']
freguesia_db.head(5)

  Current Freguesias        Area                            Old Freguesias
0      Santo António  1494348.58  Coração de Jesus + São José + São Mamede
1  Parque das Nações  5435124.30                  Santa Maria dos Olivais
2            Marvila  7122521.90                                   Marvila
3              Ajuda  2876647.11                                     Ajuda
4            Areeiro  1719002.47           Alto do Pina + São João de Deus

In [72]:
original_health_db = pd.read_csv('CentrosSaude.csv')

In [73]:
#selecting the columns with the data that we need

health_db = original_health_db[['ACTIVIDADE_NOME', 'FREGUESIA']]
health_db.columns = ['Health Center', 'Freguesia']
health_db.head(5)

            Health Center Freguesia
0         Centro de Saúde     Belém
1  Centro de Saúde Lumiar    Lumiar
2  Centro de Saúde Lumiar    Lumiar
3         Centro de Saúde     Belém
4         Centro de Saúde     Belém

In [94]:
original_police_db = pd.read_csv('Policias.csv')
original_police_db.head(3)

,X,Y,OBJECTID,COD_SIG,IDTIPO,COD_SIG_EDIF,NOME,MORADA,TIPO_UNIDADE,TELEFONE,EMAIL,CODPOSTAL,FONTE,MORADA_RMOG,GlobalID
0,-9.124780,38.752021,1,2105705006001021,999,2105705006001,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",Esquadra de Polícia,-,-,-,PSP,Rua Ricardo Ornelas (antigo Impasse A4 do B. F...,21788845-91be-4b5d-af40-f183b0016061
1,-9.135952,38.717907,2,3100303072001001,999,3100303072001,Comando - 1ª Divisão Policial LX,"Rua da Palma, 169",Comando,213513600,-,1100-391,PSP,"Rua da Palma 169, R/C",801d5d4e-4943-421e-accb-23f56dc0d0ad
2,-9.126077,38.739351,3,302704025001001,999,302704025001,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",Esquadra de Polícia,-,-,-,PSP,"Largo Roque Laia 3A, R/C-Loja A",cc8b174b-fb7e-45f9-af5f-bbc406846953

In [95]:
police_db = original_police_db[['NOME', 'MORADA','CODPOSTAL']]
police_db.head(5)

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
1,Comando - 1ª Divisão Policial LX,"Rua da Palma, 169",1100-391
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
4,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524

In [96]:
nopostcode = police_db[police_db['CODPOSTAL'] == '-']
nopostcode

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
5,Secção de Achados,Alameda das Comunidades Portuguesas Terminal 1...,-
81,Esquadra de Turismo,Largo do Museu de Artilharia,-

In [97]:
police_db.shape

(90, 3)

In [98]:
police_db[['CODPOSTAL']]

   CODPOSTAL
0          -
1   1100-391
2          -
3          -
4   1100-524
..       ...
85  1750-184
86  1750-184
87  1990-097
88  1750-184
89  1750-184

[90 rows x 1 columns]

In [99]:
#police_db['Freguesia'] = police_db['CODPOSTAL']
police_db

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
1,Comando - 1ª Divisão Policial LX,"Rua da Palma, 169",1100-391
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
4,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524
...,...,...,...
85,Brigada de Prevenção Criminal,"Avenida Maria Helena Vieira da Silva, 48",1750-184
86,Esquadra de Sinistralidade Rodoviária,"Avenida Maria Helena Vieira da Silva, 48",1750-184
87,1ª Esquadra de Transito,"Avenida Dom João II, Parque das Nações - Piso C1",1990-097
88,2ª Esquadra de Transito,"Avenida Maria Helena Vieira da Silva, 48",1750-184
89,Secção de Contra-Ordenações,"Avenida Maria Helena Vieira da Silva, 48",1750-184

In [100]:
#find duplicated addresses and remove them. Consider these as one police division
police_db.drop_duplicates(subset ="MORADA", keep = False, inplace = True) 
police_db

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
4,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524
5,Secção de Achados,Alameda das Comunidades Portuguesas Terminal 1...,-
16,Divisão Policial de Segurança a Transportes Pú...,Estação CP Rossio Ed. Posto do Comando,1200-147
17,1ª Esquadra de Segurança a Transportes Públicos,Praça do Marquês de Pombal Estação de Metro (M...,1250-161
18,Esquadra de Investigação Criminal,"Estação CP Rossio, Edifício do Chefe da Estação",1200-147
19,Tribunal de Monsanto - Esquadra Especial,Estrada do Forte (Monsanto) Tribunal,1500-624
21,4º Esquadra de Segurança a Transportes Públicos,"Avenida Dom João II, Estação do Oriente Lt. 01...",1990-233
26,Direção Nacional da PSP - Departamento de Arma...,"Travessa da Fábrica dos Pentes 22, 1º",1269-003
27,Instituto Superior de Ciências Policiais e Seg...,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
28,Carreira de Tiro da Escola Superior de Polícia,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
29,Corpo de Intervenção,"Calçada da Ajuda, 23",1300-006
30,Secção de Achados,"Praça Cidade de Salazar Lote 180, R/C",1800-125
31,Esquadra de Turismo,Praça dos Restauradores - Palácio Foz,1250-187
32,Posto de Polícia,"Rua José António Serrano Bloco Central, R/C",1150-199
33,Posto de Polícia,Avenida Professor Egas Moniz Hospital de San...,1649-035
34,Posto de Polícia,Estrada do Forte do Alto do Duque Hospital S F...,1449-005
35,Parque de Viaturas Rebocadas,"Azinhaga Torre do Fato, s/n",1600-298
36,Parque de Viaturas Rebocadas,"Rua Gregório Lopes, PSP",1400-195
37,Polícia Municipal,"Rua Cardeal Saraiva, R/C",1070-045
38,3ª Esquadra,"Rua da Atalaia 138-144, R/C, Rua de O Século ...",1200-033
40,22ª Esquadra LX,"Largo do Rato, 1",1250-185
41,2ª Divisão Policial LX,Rua Cidade de Nampula (antiga Rua B2 de Olivai...,1800-105
43,Esquadra de Intervenção e Fiscalização Policial,"Avenida Cidade Lourenço Marques, Praceta A",1800-093
44,14ª Esquadra LX,Rua Luiz Pacheco Lote 105,1950-244
45,16ª Esquadra LX,"Avenida João Paulo II Lote 526, R/C",1950-159
47,40ª Esquadra,"Rua Ilha dos Amores, Lote 43901-J, Parque das ...",1990-371
48,3ª Divisão Policial LX,"Rua André de Resende, R/C",1500-040
49,Esquadra de Segurança,"Palácio de Belém, s/n",1349-022
50,Esquadra de Segurança,"Praça de São Bento, s/n",1249-068
51,Esquadra de Segurança,"Rua Professor Gomes Teixeira 2, R/C",1350-265
52,Esquadra de Segurança,"Rua da Imprensa à Estrela, 4",1200-888
53,Esquadra de Segurança,"Avenida João Crisóstomo Casa da Moeda, R/C",1500-624
56,Esquadra de Intervenção e Fiscalização Policial,"Rua André de Resende, 1",1500-040
57,18ª Esquadra LX,"Rua Afonso Lopes Vieira 2A, R/C",1700-093
58,19ª Esquadra LX,"Rua Professor Luís Reis dos Santos, Lote H - 4...",1600-641
59,20ª Esquadra LX,Rua André de Resende 1,1500-040
60,21ª Esquadra LX,"Rua Marquês de Fronteira Tribunal da Policia, ...",1098-001
61,32ª Esquadra,Rua Alfredo Ferraz (antigo Impasse B1 do Bairr...,1600-003
62,36ª Esquadra,Rua Prof. Miller Guerra (antigo Impasse A do B...,1600-647
63,37ª Esquadra,"Rua Miguel Ângelo de Blasco 25, R/C",1070-181
64,41ª Esquadra,"Rua Maria José da Guia, 14 B - Bairro da Cruz ...",1750-358
65,42ª Esquadra,"Rua Manuela Porto, 14 - A",1500-422
66,43ª Esquadra LX,Rua do Azevinho (Rua B) Quarteirão Central B -...,1500-536
67,Posto de Polícia,Rua Albert Einstein (antiga R Norte - C.C.Colo...,1500-676
68,4ª Divisão Policial,"Largo do Calvário 6, 1º",1300-113
71,24ª Esquadra LX,"Rua Azedo Gneco 84, R/C",1350-039
72,26ª Esquadra LX,"Praça Afonso de Albuquerque PSP, R/C",1300-004
73,28ª Esquadra LX,"Largo do Calvário 6, R/C",1300-113
74,30ª Esquadra,"Rua Miguel Lupi 6, R/C",1200-725
78,10ª Esquadra Lx,"Rua de Arroios, 164 - A",1000-061
80,12ª Esquadra LX,"Rua Américo Durão, 3, A-B",1900-063
81,Esquadra de Turismo,Largo do Museu de Artilharia,-

In [114]:
#drop all rows with - on postal code
police_db.drop(police_db[police_db['CODPOSTAL'] == '-'].index, axis=0, inplace=True)

C:\Users\user\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [116]:
#resetting the index

police_db.reset_index(drop=True, inplace=True)
police_db

,NOME,MORADA,CODPOSTAL
0,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524
1,Divisão Policial de Segurança a Transportes Pú...,Estação CP Rossio Ed. Posto do Comando,1200-147
2,1ª Esquadra de Segurança a Transportes Públicos,Praça do Marquês de Pombal Estação de Metro (M...,1250-161
3,Esquadra de Investigação Criminal,"Estação CP Rossio, Edifício do Chefe da Estação",1200-147
4,Tribunal de Monsanto - Esquadra Especial,Estrada do Forte (Monsanto) Tribunal,1500-624
5,4º Esquadra de Segurança a Transportes Públicos,"Avenida Dom João II, Estação do Oriente Lt. 01...",1990-233
6,Direção Nacional da PSP - Departamento de Arma...,"Travessa da Fábrica dos Pentes 22, 1º",1269-003
7,Instituto Superior de Ciências Policiais e Seg...,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
8,Carreira de Tiro da Escola Superior de Polícia,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
9,Corpo de Intervenção,"Calçada da Ajuda, 23",1300-006
10,Secção de Achados,"Praça Cidade de Salazar Lote 180, R/C",1800-125
11,Esquadra de Turismo,Praça dos Restauradores - Palácio Foz,1250-187
12,Posto de Polícia,"Rua José António Serrano Bloco Central, R/C",1150-199
13,Posto de Polícia,Avenida Professor Egas Moniz Hospital de San...,1649-035
14,Posto de Polícia,Estrada do Forte do Alto do Duque Hospital S F...,1449-005
15,Parque de Viaturas Rebocadas,"Azinhaga Torre do Fato, s/n",1600-298
16,Parque de Viaturas Rebocadas,"Rua Gregório Lopes, PSP",1400-195
17,Polícia Municipal,"Rua Cardeal Saraiva, R/C",1070-045
18,3ª Esquadra,"Rua da Atalaia 138-144, R/C, Rua de O Século ...",1200-033
19,22ª Esquadra LX,"Largo do Rato, 1",1250-185
20,2ª Divisão Policial LX,Rua Cidade de Nampula (antiga Rua B2 de Olivai...,1800-105
21,Esquadra de Intervenção e Fiscalização Policial,"Avenida Cidade Lourenço Marques, Praceta A",1800-093
22,14ª Esquadra LX,Rua Luiz Pacheco Lote 105,1950-244
23,16ª Esquadra LX,"Avenida João Paulo II Lote 526, R/C",1950-159
24,40ª Esquadra,"Rua Ilha dos Amores, Lote 43901-J, Parque das ...",1990-371
25,3ª Divisão Policial LX,"Rua André de Resende, R/C",1500-040
26,Esquadra de Segurança,"Palácio de Belém, s/n",1349-022
27,Esquadra de Segurança,"Praça de São Bento, s/n",1249-068
28,Esquadra de Segurança,"Rua Professor Gomes Teixeira 2, R/C",1350-265
29,Esquadra de Segurança,"Rua da Imprensa à Estrela, 4",1200-888
30,Esquadra de Segurança,"Avenida João Crisóstomo Casa da Moeda, R/C",1500-624
31,Esquadra de Intervenção e Fiscalização Policial,"Rua André de Resende, 1",1500-040
32,18ª Esquadra LX,"Rua Afonso Lopes Vieira 2A, R/C",1700-093
33,19ª Esquadra LX,"Rua Professor Luís Reis dos Santos, Lote H - 4...",1600-641
34,20ª Esquadra LX,Rua André de Resende 1,1500-040
35,21ª Esquadra LX,"Rua Marquês de Fronteira Tribunal da Policia, ...",1098-001
36,32ª Esquadra,Rua Alfredo Ferraz (antigo Impasse B1 do Bairr...,1600-003
37,36ª Esquadra,Rua Prof. Miller Guerra (antigo Impasse A do B...,1600-647
38,37ª Esquadra,"Rua Miguel Ângelo de Blasco 25, R/C",1070-181
39,41ª Esquadra,"Rua Maria José da Guia, 14 B - Bairro da Cruz ...",1750-358
40,42ª Esquadra,"Rua Manuela Porto, 14 - A",1500-422
41,43ª Esquadra LX,Rua do Azevinho (Rua B) Quarteirão Central B -...,1500-536
42,Posto de Polícia,Rua Albert Einstein (antiga R Norte - C.C.Colo...,1500-676
43,4ª Divisão Policial,"Largo do Calvário 6, 1º",1300-113
44,24ª Esquadra LX,"Rua Azedo Gneco 84, R/C",1350-039
45,26ª Esquadra LX,"Praça Afonso de Albuquerque PSP, R/C",1300-004
46,28ª Esquadra LX,"Largo do Calvário 6, R/C",1300-113
47,30ª Esquadra,"Rua Miguel Lupi 6, R/C",1200-725
48,10ª Esquadra Lx,"Rua de Arroios, 164 - A",1000-061
49,12ª Esquadra LX,"Rua Américo Durão, 3, A-B",1900-063